<?php

require_once dirname(__FILE__) . '/../../lib/IssuuMessage.php';
require_once dirname(__FILE__) . '/../../lib/IssuuResponse.php';

/**
 * Test class for IssuuResponse.
 * Generated by PHPUnit on 2011-05-19 at 11:24:30.
 */
class IssuuResponseTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var IssuuResponse
   */
  protected $response;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->response = new IssuuResponse;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  public function testArrayAccessImplementation()
  {
    $this->response['fooParam1'] = 'fooValue1';
    $this->response['fooParam2'] = 'fooValue2';

    $this->assertEquals('fooValue1', $this->response['fooParam1']);
    $this->assertEquals('fooValue2', $this->response['fooParam2']);
  }

}

?>
