<?php

require_once dirname(__FILE__) . '/../../lib/IssuuMessage.php';
require_once dirname(__FILE__) . '/../../lib/IssuuRequest.php';

/**
 * Test class for IssuuRequest.
 * Generated by PHPUnit on 2011-05-19 at 10:54:38.
 */
class IssuuRequestTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var IssuuRequest
   */
  protected $request;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->request = new IssuuRequest;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  public function testArrayAccessImplementation()
  {
    $this->request['fooParam1'] = 'fooValue1';
    $this->request['fooParam2'] = 'fooValue2';
    
    $this->assertEquals('fooValue1', $this->request['fooParam1']);
    $this->assertEquals('fooValue2', $this->request['fooParam2']);
  }
  
  /**
   * @expectedException BadMethodCallException
   */
  public function testArrayAccessInvalidValue()
  {
    $this->request[] = 'invalidParameterAssignment';
  }
  
}

?>
