<?php

require_once dirname(__FILE__) . '/../../lib/IssuuMessage.php';
require_once dirname(__FILE__) . '/../../lib/IssuuResponse.php';

/**
 * Test class for IssuuResponse.
 * Generated by PHPUnit on 2011-05-19 at 11:24:30.
 */
class IssuuResponseTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var IssuuResponse
   */
  protected $response;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->response = new IssuuResponse;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  public function testArrayAccessImplementation()
  {
    $this->response['fooParam1'] = 'fooValue1';
    $this->response['fooParam2'] = 'fooValue2';

    $this->assertEquals('fooValue1', $this->response['fooParam1']);
    $this->assertEquals('fooValue2', $this->response['fooParam2']);
  }

  public function testPopulateFromResponseBody()
  {
    $rsp = <<<EOF
<rsp stat="ok"> 
  <document username="lekkim" name="racing" documentId="090623122351-f691a27cfd744b80b25a2c8f5a51d596" title="fooDocumentTitle" access="public" state="P" category="012000" type="009000" origin="singleupload" pageCount="0" ep="1245759831" description="Race cars of Le Man 2009"> 
    <tags> 
      <tag value="cars"/> 
      <tag value="le man"/> 
      <tag value="racing"/> 
    </tags> 
    <folders> 
      <folder id="3935f331-5d5b-4694-86ce-6f26c6dee809"/> 
    </folders> 
  </document> 
</rsp>
EOF;
    $this->response->populateFromResponseBody($rsp);
    
    $this->assertEquals('090623122351-f691a27cfd744b80b25a2c8f5a51d596', $this->response['documentId']);
    $this->assertEquals('fooDocumentTitle', $this->response['title']);
    $this->assertEquals('lekkim', $this->response['username']);
    $this->assertEquals('racing', $this->response['name']);
  }
}

?>
